#!/bin/bash
#
# osg-cleanup-cron  This shell script enables the automatic use of osg-cleanup
#
# Based on fetch-crl-cron script
#
# chkconfig:	- 51 01
#
# description:  Enable daily run of osg-cleanup, a script to remove old files.
# processname:  osg-cleanup-cron
# config: /etc/osg/osg-cleanup.conf
#

# source function library
. /etc/rc.d/init.d/functions

lockfile=/var/lock/subsys/osg-cleanup-cron

RETVAL=0

start() {
	action $"Enabling periodic osg-cleanup: " touch "$lockfile" 
	RETVAL=$?
}

stop() {
	action $"Disabling periodic osg-cleanup: " rm -f "$lockfile" 
	RETVAL=$?
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop) 
	stop
	;;
  restart|force-reload)
	restart
	;;
  reload)
	;;
  condrestart)
	[ -f "$lockfile" ] && restart
	;;
  status)
	if [ -f $lockfile ]; then
		echo $"Periodic osg-cleanup is enabled."
		RETVAL=0
	else
		echo $"Periodic osg-cleanup is disabled."
		RETVAL=3
	fi
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
	exit 1
esac

exit $RETVAL
